name: CI check

on:
  push:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.24.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint
